

ACTION_IF Sharteel_portrait = 1 THEN BEGIN

// Shar-Teels neue Portraits kopieren
	COPY ~Sharteel_BG2/Portraits/sharL.bmp~ ~override/JOsharL.bmp~
	COPY ~Sharteel_BG2/Portraits/sharS.bmp~ ~override/JOsharS.bmp~

END

// Shar-Teels Soundset kopieren
//	COPY ~Sharteel_BG2/Sounds/shar1.wav~ ~override/JOshar1.wav~
//	COPY ~Sharteel_BG2/Sounds/shart.wav~ ~override/JOshart.wav~
//	COPY ~Sharteel_BG2/Sounds/sharu.wav~ ~override/JOsharu.wav~
//	COPY ~Sharteel_BG2/Sounds/sharb.wav~ ~override/JOsharb.wav~
//	COPY ~Sharteel_BG2/Sounds/sharc.wav~ ~override/JOsharc.wav~
//	COPY ~Sharteel_BG2/Sounds/shard.wav~ ~override/JOshard.wav~
//	COPY ~Sharteel_BG2/Sounds/shara.wav~ ~override/JOshara.wav~
//	COPY ~Sharteel_BG2/Sounds/shar9.wav~ ~override/JOshar9.wav~
	COPY ~Sharteel_BG2/Sounds/shar8.wav~ ~override/JOshar8.wav~
//	COPY ~Sharteel_BG2/Sounds/sharl.wav~ ~override/JOsharl.wav~
//	COPY ~Sharteel_BG2/Sounds/sharm.wav~ ~override/JOsharm.wav~
//	COPY ~Sharteel_BG2/Sounds/sharf.wav~ ~override/JOsharf.wav~
//	COPY ~Sharteel_BG2/Sounds/sharg.wav~ ~override/JOsharg.wav~
//	COPY ~Sharteel_BG2/Sounds/sharh.wav~ ~override/JOsharh.wav~
//	COPY ~Sharteel_BG2/Sounds/sharx.wav~ ~override/JOsharx.wav~
//	COPY ~Sharteel_BG2/Sounds/shary.wav~ ~override/JOshary.wav~
//	COPY ~Sharteel_BG2/Sounds/shari.wav~ ~override/JOshari.wav~
//	COPY ~Sharteel_BG2/Sounds/sharj.wav~ ~override/JOsharj.wav~
//	COPY ~Sharteel_BG2/Sounds/shark.wav~ ~override/JOshark.wav~
//	COPY ~Sharteel_BG2/Sounds/shars.wav~ ~override/JOshars.wav~
//	COPY ~Sharteel_BG2/Sounds/sharv.wav~ ~override/JOsharv.wav~

// Charakterscript kopieren
	COMPILE ~Sharteel_BG2/Baf/JOsharte.baf~

// CRE kopieren, Namensgebung, Setzen der Biographie, Eintrag der Sounds
	COPY ~Sharteel_BG2/Cre/shartel.cre~ ~override/JOsharte.cre~
		SAY NAME1 @100 /* Shar-Teel */
		SAY NAME2 @100 /* Shar-Teel */
		SAY BIO @101 /* Als Ihr SHAR-TEEL nach ihrer Vergangenheit fragt, sagt sie nicht viel. Von dem wenigen, das sie erzählt, könnt Ihr schließen, dass sie eine Waise ist. Sie scheint auch eine ausgeprägte Abneigung gegenüber Söldnern der Flammenden Faust zu hegen, ebenso eine offensichtliche Respektlosigkeit gegenüber Männern im allgemeinen. Sie scheint sich etwas beweisen zu müssen und wahrscheinlich hatte sie nicht unbedingt eine Bilderbuch-Kindheit. */
		SAY INITIAL_MEETING #3608 // @102 /* Ich scheiß auf Eure Männlichkeit! */
		SAY HAPPY #3595 // @103 /* Feinde niedermetzeln...bringt Freude ins Leben. */
		SAY UNHAPPY_ANNOYED #3597 // @104 /* Das Schwert ist das Einzige, worauf sich eine Frau verlassen kann. */
		SAY LEADER #3583 // @105 /* Ich werde diese Gruppe besser anführen, als es ein Mann jemals könnte. */
		SAY TIRED #3584 // @106 /* Kleine Pause geht in Ordnung... */
		SAY BORED #3585 // @107 /* Reine Zeitverschwendung, besser gesagt 'Männer' sind reine Zeitverschwendung. */
		SAY BATTLE_CRY1 #3590 // @108 /* Wenn es blutet kann ich es auch töten. */
		SAY BATTLE_CRY2 #3611 // @109 /* das Schwein hat es heraufbeschwört. */
		SAY BATTLE_CRY3 @110 /* Lasst Euch von keinem Mann einschüchtern. */
		SAY DAMAGE #5276 // @111 /*  */
		SAY DYING #5280 // @112 /*  */
		SAY SELECT_COMMON1 #3577 // @113 /* Vorsicht ist heldenhafter als Mut. */
		SAY SELECT_COMMON2 #3589 // @114 /* Männer sind so armselig. */
		SAY SELECT_COMMON3 #3591 // @115 /* Hm...ich liebe Blutvergießen. */
		SAY SELECT_COMMON4 #3598 // @116 /* Männer denken niemals mit ihrem Gehirn. */
		SAY SELECT_COMMON5 #3607 // @117 /* Nutzloser stinkender männlicher Dreckhaufen. */
		SAY SELECT_ACTION1 #3592 // @118 /* Ok. */
		SAY SELECT_ACTION2 #3593 // @119 /* Wirklich? */
		SAY SELECT_ACTION3 #3594 // @120 /* Ich tue es. */
		SAY SELECT_ACTION4 #3596 // @121 /* Manchmal bringt mich schon der Geruch eines Mannes zum Würgen. */
		SAY SELECT_ACTION5 #3595 // @122 /* Feinde niedermetzeln bringt Freude ins Leben. */
		SAY SELECT_ACTION6 #3597 // @104 /* Das Schwert ist das Einzige, worauf sich eine Frau verlassen kann. */
		SAY SELECT_ACTION7 #3604 // @123 /* Mit Schmeicheleien kommt Ihr bei mir nicht weiter. */
WRITE_ASCIIE 0x034 ~%sharS%~ (8)	// Small portrait
WRITE_ASCIIE 0x03c ~%sharL%~ (8)	// Large portrait
// WRITE_BYTE 0x270 ~128~ // Allegiance neutral
WRITE_ASCII SCRIPT_OVERRIDE ~JOsharte~  #8
WRITE_ASCII DIALOG ~JOchar~  #8
WRITE_ASCII DEATHVAR ~sharteel~ (32)

// Gebietscripte ergänzen
EXTEND_BOTTOM ~AR0602.bcs~ ~Sharteel_BG2/Baf/Arshar.baf~
EXTEND_BOTTOM ~AR0406.bcs~ ~Sharteel_BG2/Baf/AR0406.baf~

ACTION_IF GAME_IS ~bg2ee eet~ BEGIN
	OUTER_SPRINT "XEquipItem_sword2" ~XEquipItem("SW1H04","sharteel",SLOT_SHIELD,EQUIP)~
	OUTER_SPRINT "XEquipItem_sword" ~XEquipItem("SW1H04","sharteel",SLOT_WEAPON1,EQUIP)~
	OUTER_SPRINT "XEquipItem_armor" ~XEquipItem("LEAT04","sharteel",SLOT_ARMOR,EQUIP)~
	OUTER_SPRINT "XEquipItem_helm" ~XEquipItem("HELM01","sharteel",SLOT_HELM,EQUIP)~
END ELSE BEGIN
	OUTER_SPRINT "XEquipItem_helm" ~ActionOverride("sharteel",EquipItem("HELM01"))~
	OUTER_SPRINT "XEquipItem_armor" ~ActionOverride("sharteel",EquipItem("LEAT04"))~
	OUTER_SPRINT "XEquipItem_sword" ~ActionOverride("sharteel",EquipItem("SW1H04"))~
	OUTER_SPRINT "XEquipItem_sword2" ~~
END

ACTION_IF GAME_IS ~eet~ BEGIN

	OUTER_SPRINT "Spawn_Area" ~AR0602~
	OUTER_SPRINT "Spawn_Point" ~1434.1524~
	
	EXTEND_BOTTOM ~AR0602.bcs~ ~Sharteel_BG2/Baf/Continuous_sharteel.baf~ EVALUATE_BUFFER
	
	OUTER_SPRINT "Spawn_Area" ~AR0406~
	OUTER_SPRINT "Spawn_Point" ~681.1094~
	
	EXTEND_BOTTOM ~AR0406.bcs~ ~Sharteel_BG2/Baf/Continuous_sharteel.baf~ EVALUATE_BUFFER
	
END

// Dialoge in 2da's hinzufügen	//  sharteel ?

APPEND ~pdialog.2da~ ~SHARTEEL     JOcharP     JOcharJ     JOcharD~
	UNLESS ~SHARTEEL~
		UNLESS ~25POST~

APPEND ~pdialog.2da~ ~SHARTEEL     JOcharP     JOcharJ     JOcharD     JOchar25P     JOchar25J     JOchar25D~
	UNLESS ~SHARTEEL~
		IF ~25POST~

COMPILE EVALUATE_BUFFER ~Sharteel_BG2/Dialogs/charJ.d~
COMPILE EVALUATE_BUFFER ~Sharteel_BG2/Dialogs/charP.d~
COMPILE EVALUATE_BUFFER ~Sharteel_BG2/Dialogs/JOchar25.d~

	// Variable used by FUNCTION GW_FIND_DLG_RESPONSE_STRING to find after which transition NPC will be recalled by Fate Spirit.
			OUTER_SET fatesp_string = 83364  // Rasaad = @83364  = ~Amenez-moi Rasaad, le moine de la Conscience Solaire humain.~

ACTION_IF GAME_IS ~eet~ BEGIN
  INCLUDE ~EET/other/EET_functions.tph~
  LAF ~EET_NPC_TRANSITION~
    INT_VAR
      type = 2
      default_ToB = 1
      clean_ToB = 1
    STR_VAR
      dv = "sharteel"
      override_SoA = "JOsharte"
//      override_ToB = "xxxxx25S"
      dialog_ToB = "JOchar25"
      cre_ToB = "JOsharte"
      traFile = EVAL "weidu_external/Sharteel_BG2/Languages/autotra/%LANGUAGE%/setup.tra"
      string = "@3"
      stringPosDV = "Safana"
      clean_ToB_DV = "sharteel"
  END
END ELSE BEGIN
		INCLUDE ~Sharteel_BG2/lib/gw_dlg_functions.tpa~
  COMPILE EVALUATE_BUFFER ~Sharteel_BG2/Dialogs/FATESP.d~ USING ~weidu_external/Sharteel_BG2/Languages/autotra/%LANGUAGE%/setup.tra~
END
