
IF
	Global("shartFirstTalk","GLOBAL",0) // Set to 1 in charJ.d if player already talk to Sharteel in Irenicus donjon
	Global("Continuous_BG2_Sharteel","MYAREA",0)
	OR(2)
		BeenInParty("sharteel")
		Exists("sharteel")
	!Dead("sharteel")
	!InPartyAllowDead("sharteel")
	!InParty("sharteel")
	!InMyArea("sharteel")
THEN
	RESPONSE #100
		SetInterrupt(FALSE)
		SetGlobal("Continuous_BG2_Sharteel","MYAREA",1)
		MoveGlobal("%Spawn_Area%","sharteel",[%Spawn_Point%])
		ApplySpellRES("bdresurr","sharteel")
		SmallWait(1)
		ReallyForceSpellDeadRES("bdrejuve","sharteel")
		ChangeEnemyAlly("sharteel",NEUTRAL)
		ChangeSpecifics("sharteel",ALLIES)
		ActionOverride("sharteel",SetNumTimesTalkedTo(0))
//		ActionOverride("sharteel",SetGlobal("bd_joined","locals",0)) // SoD
		ActionOverride("sharteel",ChangeAIScript("JOsharte",OVERRIDE))
//		ActionOverride("sharteel",ChangeAIScript("",CLASS))
//		ActionOverride("sharteel",ChangeAIScript("",RACE))
//		ActionOverride("sharteel",ChangeAIScript("",GENERAL))
//		ActionOverride("sharteel",ChangeAIScript("",DEFAULT))
		ActionOverride("sharteel",SetDialog("JOchar"))
//		ActionOverride("sharteel",DestroyAllEquipment())
		ActionOverride("Jailkeep Table",TakeCreatureItems("sharteel",ALL))
		GiveItemCreate("HELM01","sharteel",0,0,0)
		GiveItemCreate("LEAT04","sharteel",0,0,0)
		GiveItemCreate("SW1H04","sharteel",0,0,0)
		GiveItemCreate("POTN52","sharteel",4,0,0)
		%XEquipItem_armor%
		%XEquipItem_sword%
		%XEquipItem_helm%
		GiveItemCreate("SW1H04","sharteel",0,0,0)
		%XEquipItem_sword2%
		SetInterrupt(TRUE)
		Continue()
END
